

service: eidlan-point-bot

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  timeout: 20






functions:
  hello:
    handler: handler.hello

    events:
       - http: ANY /{proxy+}
       - http: ANY /
    environment:
       BOT_TOKEN: OTUyNjEwNjE2MjY1MzAyMDM4.Yi4hxQ.KLpAJ3SAk_Vrh7G04TyqY27Fh3w
       DB_HOST: eid-bot-db.ctsalrqcpdkm.ap-southeast-1.rds.amazonaws.com
       DB_USER: eidland1234
       DB_PASSWORD: eidland1234
       DB_DATABASE: eidBot
       DB_PORT: 3306

